In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
unfaelle = gpd.read_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\unfaelle_zuerich_2023_temporegime_beleuchtung.json")

In [3]:
zebrastreifen = gpd.read_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\zebrastreifen.geojson")

In [4]:
zebrastreifen.head(2)

,id,@id,access,bicycle,bottle,bridge,button_operated,check_date:surface,covered,crossing,...,traffic_calming,traffic_signals:direction,traffic_signals:sound,trail_visibility,tunnel,vehicle,wheelchair,width,wikidata,geometry
0,way/4249069,way/4249069,None,None,None,None,None,None,None,marked,...,None,None,None,None,None,None,None,None,None,"LINESTRING (8.76031 47.50162, 8.76042 47.50164..."
1,way/4249220,way/4249220,None,yes,None,None,None,None,None,marked,...,None,None,None,None,None,None,None,None,None,"LINESTRING (8.70679 47.49458, 8.70685 47.49463..."

In [5]:
zebrastreifen.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 11462 entries, 0 to 11461
Data columns (total 70 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         11462 non-null  object
 1   @id                        11462 non-null  object
 2   access                     27 non-null     object
 3   bicycle                    775 non-null    object
 4   bottle                     1 non-null      object
 5   bridge                     29 non-null     object
 6   button_operated            8 non-null      object
 7   check_date:surface         25 non-null     object
 8   covered                    3 non-null      object
 9   crossing                   7822 non-null   object
 10  crossing:island            908 non-null    object
 11  crossing:markings          1375 non-null   object
 12  crossing:markings:colour   314 non-null    object
 13  crossing:signals           1 non-null      object
 14  crossing_ref               36 non-null     object
 15  cycleway                   5 non-null      object
 16  cycleway:surface           57 non-null     object
 17  cycleway:width             2 non-null      object
 18  dog                        1 non-null      object
 19  emergency                  5 non-null      object
 20  est_width                  2 non-null      object
 21  fixme                      1 non-null      object
 22  foot                       236 non-null    object
 23  footway                    11462 non-null  object
 24  footway:surface            62 non-null     object
 25  handrail                   9 non-null      object
 26  highway                    11462 non-null  object
 27  horse                      12 non-null     object
 28  incline                    262 non-null    object
 29  kerb                       83 non-null     object
 30  layer                      33 non-null     object
 31  lcn                        86 non-null     object
 32  level                      3 non-null      object
 33  lit                        6761 non-null   object
 34  mofa                       1 non-null      object
 35  motor_vehicle              24 non-null     object
 36  motorcar                   12 non-null     object
 37  motorcycle                 10 non-null     object
 38  mtb:scale                  3 non-null      object
 39  mtb:scale:uphill           1 non-null      object
 40  name                       89 non-null     object
 41  name:etymology:wikidata    2 non-null      object
 42  noname                     4 non-null      object
 43  note                       6 non-null      object
 44  oneway                     13 non-null     object
 45  oneway:bicycle             12 non-null     object
 46  oneway:foot                4 non-null      object
 47  path                       2 non-null      object
 48  sac_scale                  11 non-null     object
 49  segregated                 229 non-null    object
 50  service                    1 non-null      object
 51  sidewalk                   1 non-null      object
 52  smoothness                 1468 non-null   object
 53  source                     3 non-null      object
 54  source:cycleway:width      1 non-null      object
 55  step_count                 1 non-null      object
 56  surface                    8449 non-null   object
 57  survey:date                1 non-null      object
 58  tactile_paving             437 non-null    object
 59  tracktype                  7 non-null      object
 60  traffic_calming            95 non-null     object
 61  traffic_signals:direction  1 non-null      object
 62  traffic_signals:sound      4 non-null      object
 63  trail_visibility           2 non-null      object
 64  tunnel                     2 non-null      object
 65  vehicle                    22 non-null     object
 66  wheelchair                 4 non-null      object
 67  width                      172 non-null    object
 68  wikidata                   33 non-null     object
 69  geometry                   11462 non-null  geometry
dtypes: geometry(1), object(69)
memory usage: 6.1+ MB

In [6]:
# nur id und geometry behalten
zebrastreifen = zebrastreifen[['id', 'geometry']]

In [7]:
zebrastreifen

                   id                                           geometry
0         way/4249069  LINESTRING (8.76031 47.50162, 8.76042 47.50164...
1         way/4249220  LINESTRING (8.70679 47.49458, 8.70685 47.49463...
2         way/4249264  LINESTRING (8.75085 47.48914, 8.75079 47.48909...
3         way/4249334  LINESTRING (8.74597 47.49808, 8.74580 47.49808...
4         way/4249453  LINESTRING (8.76275 47.49793, 8.76280 47.49793...
...               ...                                                ...
11457  way/1321926544    LINESTRING (8.67021 47.52223, 8.67017 47.52221)
11458  way/1321926990    LINESTRING (8.67173 47.52963, 8.67171 47.52967)
11459  way/1321926991    LINESTRING (8.67176 47.52959, 8.67175 47.52961)
11460  way/1321938504    LINESTRING (8.67058 47.47111, 8.67061 47.47113)
11461  way/1322085593    LINESTRING (8.53096 47.36473, 8.53094 47.36474)

[11462 rows x 2 columns]

In [8]:
# Erstelle eine Spalte "Zebrastreifen"
# Suche für jeden Unfall den nächsten Zebrastreifen und speichere die Distanz in die Spalte "Zebrastreifen"
unfaelle = unfaelle.to_crs(epsg=2056)
zebrastreifen = zebrastreifen.to_crs(epsg=2056)


unfaelle['Zebrastreifen'] = unfaelle.apply(lambda x: zebrastreifen.distance(x['geometry']).min(), axis=1)

unfaelle.head(2)

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,...,Jahr,Monat,Wochentag,Stunde,Stunde_text,Temporegime,distance_to_light,keine_beleuchtung,geometry,Zebrastreifen
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,...,2016,Januar,Mittwoch,16,16h-17h,50 km/h,1.56339,False,POINT (2681186.001 1247896.002),0.146857
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,...,2016,Januar,Freitag,13,13h-14h,50 km/h,4.42894,False,POINT (2682739.001 1244360.002),3.802592

In [9]:
unfaelle = unfaelle.to_crs(epsg=4326)

In [10]:
# Unfaelle "Zebrastreifen" = True wenn Distanz kleiner als 5m
unfaelle['Zebrastreifen'] = unfaelle['Zebrastreifen'] < 2

unfaelle.head(2)

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,...,Jahr,Monat,Wochentag,Stunde,Stunde_text,Temporegime,distance_to_light,keine_beleuchtung,geometry,Zebrastreifen
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,...,2016,Januar,Mittwoch,16,16h-17h,50 km/h,1.56339,False,POINT (8.51365 47.37690),True
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,...,2016,Januar,Freitag,13,13h-14h,50 km/h,4.42894,False,POINT (8.53356 47.34490),False

In [11]:
unfaelle.head(2)

,UnfallID,Unfallart,Unfallschwere,Fussgänger_beteiligt,Fahrrad_beteiligt,Motorrad_beteiligt,Strassentyp,Unfallort_Lon,Unfallort_Lat,Kanton,...,Jahr,Monat,Wochentag,Stunde,Stunde_text,Temporegime,distance_to_light,keine_beleuchtung,geometry,Zebrastreifen
0,2AF2FBACB62B00DAE0530A8394273CC3,Fussgängerunfall,Unfall mit Leichtverletzten,true,true,false,Nebenstrasse,2681186,1247896,ZH,...,2016,Januar,Mittwoch,16,16h-17h,50 km/h,1.56339,False,POINT (8.51365 47.37690),True
1,2B51E1C5A119015CE0530A839427323A,Schleuder- oder Selbstunfall,Unfall mit Leichtverletzten,false,true,false,Hauptstrasse,2682739,1244360,ZH,...,2016,Januar,Freitag,13,13h-14h,50 km/h,4.42894,False,POINT (8.53356 47.34490),False

In [12]:
# Plotte die Unfälle mit plotly
import plotly.express as px

fig = px.scatter_mapbox(unfaelle, lat=unfaelle.geometry.y, lon=unfaelle.geometry.x, color='Zebrastreifen', hover_name='Zebrastreifen')
fig.update_layout(mapbox_style="open-street-map")

fig.show()

In [13]:
# Speichere die Daten
unfaelle.to_file(r"C:\Users\leoni\Documents\HSLU\5. Semester\Informationsvisualisierung\Einzelprojekt\informationsvisualisierung-leonid-wouters\Daten\unfaelle_zuerich_2023_temporegime_beleuchtung_zebrastreifen.json", driver='GeoJSON')